name: Publish package to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          always-auth: 'true'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@deepaksinghkhetwal'

      - run: npx playwright install --with-deps
      - run: npm ci

      - run: npm run build

      - name: Set Git config
        run: |
          git config --local user.email "deepak"
          git config --local user.name "deepak"

      - run: npm version patch

      - run: git push --follow-tags

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
